"""Data export endpoints.

Two routes: a manifest describing what this caller may download, and the
download itself. The manifest exists so the UI never has to hardcode the sheet
list or duplicate the permission rules - it renders whatever comes back.
"""
from typing import List, Optional
from urllib.parse import quote

from fastapi import APIRouter, Depends, HTTPException, Query, Response
from sqlalchemy.orm import Session

from app.core.daterange import resolve_range
from app.core.database import get_db
from app.modules.auth.dependencies import granted_keys, require_permission
from app.modules.export import registry, schemas, writers
from app.modules.export.context import ExportContext
from app.modules.tasks.models import get_ist_now

router = APIRouter(prefix="/export", tags=["Export"])

#: Refused rather than materialised. The zip and workbook paths both buffer in
#: memory, so this is the line between a slow download and an OOM.
MAX_EXPORT_ROWS = 200_000

FORMATS = ["csv", "xlsx"]
GROUP_ORDER = ["Core Data", "Analytics", "Administration"]


def _context(
    db: Session,
    actor,
    start_date: Optional[str] = None,
    end_date: Optional[str] = None,
    category_id: Optional[int] = None,
    goal_id: Optional[int] = None,
    status: Optional[str] = None,
    user_id: Optional[int] = None,
    sheet_keys: Optional[List[str]] = None,
):
    """Resolves one request into a context plus the caller's permission keys."""
    keys = set(granted_keys(db, actor))
    # Admin is a superuser bypass everywhere else in the app; keep it so here.
    sees_all = actor.role == "Admin" or "data.export.all" in keys

    range_start, range_end = resolve_range(get_ist_now(), start_date, end_date)

    if user_id is not None and not sees_all and user_id != actor.id:
        raise HTTPException(
            status_code=403,
            detail="Your account can only export its own data (data.export.all is required)",
        )

    context = ExportContext(
        db=db,
        actor=actor,
        range_start=range_start,
        range_end=range_end,
        visible_user_ids=None if sees_all else {actor.id},
        category_id=category_id,
        goal_id=goal_id,
        status=status,
        user_id=user_id,
        sheet_keys=sheet_keys,
    )
    return context, keys


@router.get("/manifest", response_model=schemas.ExportManifest)
def get_manifest(
    start_date: Optional[str] = None,
    end_date: Optional[str] = None,
    db: Session = Depends(get_db),
    actor=Depends(require_permission("data.export")),
):
    """What this caller can download, and roughly how many rows each sheet holds.

    Row estimates follow the same date window the download will use, so the
    counts shown beside each checkbox match what actually arrives.
    """
    context, keys = _context(db, actor, start_date, end_date)

    sheets = [
        schemas.SheetInfo(
            key=sheet.key,
            label=sheet.label,
            group=sheet.group,
            description=sheet.description,
            range_scoped=sheet.range_scoped,
            row_estimate=registry.row_estimate(sheet, context),
        )
        for sheet in registry.SHEETS
        if registry.allowed(sheet, keys)
    ]

    return schemas.ExportManifest(
        sheets=sheets,
        scope=context.scope,
        formats=FORMATS,
        default_sheets=[key for key in registry.DEFAULT_SHEETS
                        if any(sheet.key == key for sheet in sheets)],
        group_order=GROUP_ORDER,
    )


def _readme(context, specs) -> str:
    """Provenance for the zip, mirroring what the Summary sheet carries."""
    lines = [
        "OutcomeOriented data export",
        "=" * 27,
        "",
        f"Generated at (IST): {get_ist_now().strftime('%Y-%m-%d %H:%M:%S')}",
        f"Generated by:       {context.actor.name}",
        f"Scope:              {'All accounts' if context.sees_all_users() else f'Own data only ({context.actor.name})'}",
        f"Date range:         {context.range_label()}",
        "",
        "Timestamps are Asia/Kolkata (IST) wall-clock and carry no UTC offset.",
        "Columns suffixed _in_range honour the date range above; all others are",
        "lifetime figures.",
        "",
        "Files",
        "-----",
    ]
    for spec in specs:
        lines.append(f"{spec.sheet_name}.csv - {spec.label}: {spec.description}")
    return "\n".join(lines) + "\n"


@router.get("")
def download_export(
    format: str = Query("xlsx", pattern="^(csv|xlsx)$"),
    sheets: str = Query("", description="Comma-separated sheet keys"),
    start_date: Optional[str] = None,
    end_date: Optional[str] = None,
    category_id: Optional[int] = None,
    goal_id: Optional[int] = None,
    status: Optional[str] = None,
    user_id: Optional[int] = None,
    db: Session = Depends(get_db),
    actor=Depends(require_permission("data.export")),
):
    """Builds the requested sheets and returns them as one file.

    xlsx is always a single workbook. csv is a bare file for one sheet and a zip
    for several, because a browser can only accept one download per request.
    """
    requested = [key.strip() for key in sheets.split(",") if key.strip()]
    if not requested:
        raise HTTPException(
            status_code=400,
            detail=f"Select at least one sheet. Available: {', '.join(registry.SHEET_KEYS)}",
        )

    unknown = registry.unknown_keys(requested)
    if unknown:
        raise HTTPException(
            status_code=400,
            detail=f"Unknown sheet(s): {', '.join(unknown)}. "
                   f"Available: {', '.join(registry.SHEET_KEYS)}",
        )

    specs = registry.resolve(requested)
    context, keys = _context(
        db, actor, start_date, end_date, category_id, goal_id, status, user_id,
        sheet_keys=[spec.label for spec in specs],
    )

    for spec in specs:
        if not registry.allowed(spec, keys):
            raise HTTPException(
                status_code=403,
                detail=f"The '{spec.label}' sheet requires the {spec.permission} permission",
            )

    built = []
    for spec in specs:
        headers, rows = spec.builder(context)
        if len(rows) > MAX_EXPORT_ROWS:
            raise HTTPException(
                status_code=400,
                detail=f"The '{spec.label}' sheet would contain {len(rows):,} rows, over the "
                       f"{MAX_EXPORT_ROWS:,} limit. Narrow the date range and try again.",
            )
        built.append((spec.label, spec.sheet_name, headers, rows))

    today = get_ist_now().strftime("%Y-%m-%d")

    if format == "xlsx":
        payload = writers.write_xlsx(built)
        filename = f"outcomeoriented-export-{today}.xlsx"
        media_type = writers.XLSX_MEDIA_TYPE
    elif len(built) == 1:
        payload = writers.write_csv_single(built[0])
        filename = f"outcomeoriented-{built[0][1]}-{today}.csv"
        media_type = writers.CSV_MEDIA_TYPE
    else:
        payload = writers.write_csv_zip(built, _readme(context, specs))
        filename = f"outcomeoriented-export-{today}.zip"
        media_type = writers.ZIP_MEDIA_TYPE

    return Response(
        content=payload,
        media_type=media_type,
        headers={
            # filename* carries the UTF-8 form for clients that understand RFC 5987;
            # plain filename is the ASCII fallback.
            "Content-Disposition": (
                f'attachment; filename="{filename}"; '
                f"filename*=UTF-8''{quote(filename)}"
            ),
            "Content-Length": str(len(payload)),
            "Cache-Control": "no-store",
        },
    )
